version: "3.7"
services:
  liveterm:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '3000'
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app/
    command: npm run dev
